### PR TITLE
Add CachingMode parameter

### LINKED ISSUE #8: Feature Request: Caching Settings (Offline Settings)
Please could you kindly add the ability to disable / enable offline mode for shares.

### PR DESCRIPTION
**Pull request by MartinVokurek**
Adds CachingMode parameter to the Test and Get functions and defines
possible values (matches Set-SmbShare). Fixes #8

---

This change is [Reviewable](https://reviewable.io/reviews/powershell/xsmbshare/11)

### CODE REVIEW

**Comment by Indhukrishna** [comment]
@MartinVokurek Can you please add tests for your changes according to https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md

**Comment by claudiospizzi** [comment]
Hi @MartinVokurek 
Will you continue on this PR soon? I need the "ChachingMode" in my setup too, would be great if it will make into the upstream.

**Comment by johlju** [comment]
Labeling this as abandoned so that another contributor can continue the work.

**Comment by claudiospizzi** [comment]
@johlju 
Maybe, I have time to work on this. How can I continue with the PR, is there a process? Or can I simple redo the changes in my fork and create a new PR?

**Comment by johlju** [comment]
@claudiospizzi would be great if you can continue the work on this. Please look at [How to continue working on a pull request (PR) when an author (contributor) is unable to complete it](https://github.com/PowerShell/DscResources/blob/master/GettingStartedWithGitHub.md#how-to-continue-working-on-a-pull-request-pr-when-an-author-contributor-is-unable-to-complete-it). You can also just redo the changes in your fork, if that is simpler.

**Comment by MartinVokurek** [comment]
Hi,

@claudiospizzi feel free to continue or redo my work, I don’t think I’ll have time to finish it myself any time soon.

Regards,
Martin

**Pull request closed without merging**
