### PR TITLE
xSmbShare: Deprecating the resource module

### PR DESCRIPTION
**Pull request by johlju**
#### Pull Request (PR) description
Deprecating this resource module. 

*This PR should only be merged once the PR https://github.com/PowerShell/ComputerManagementDsc/pull/211 is merged.*

#### This Pull Request (PR) fixes the following issues
As discussed in issue https://github.com/PowerShell/DscResources/issues/374.

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the README.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsmbshare/31)

### CODE REVIEW

**Comment by johlju** [comment]
After this is merged the repository title should be updated to "THIS MODULE HAS BEEN DEPRECATED Please use SmbShare instead: https://github.com/PowerShell/ComputerManagementDsc".

**Comment by gaelcolas** [comment]
@johlju that one should be ready to go too.

**Comment by johlju** [comment]
As som as the PR is merged in ComputerManagementDsc I will merge this one.

**Review by johlju — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/powershell/xsmbshare/31#-:-Livx8rj7SBUMdhrBsUD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
